// Modules
import type { Metadata } from 'next';

// Styles
import '@/sass/style.scss';

// Components
import Header from '@/components/Header';
import MainNav from '@/components/MainNav';
import Footer from '@/components/Footer';

// Metadata
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	icons: [{ url: '/favicon.svg', type: 'image/svg+xml' }],
};

// Rendern
export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="de">
			<body>
				<Header />
				<MainNav />
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
