// Modules
import type { Metadata } from 'next';

// Styles
import '@/sass/style.scss';

// Components

// Metadata
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	icons: [{ url: '/favicon.svg', type: 'image/svg+xml' }],
};

// Rendern
export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="de">
			<body>
				<div className="site-wrapper">
					<div className="site-content">{children}</div>
				</div>
			</body>
		</html>
	);
}
